# Generated by Django 4.2.21 on 2026-04-11 13:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur"),
                            ("RESPONSABLE_STOCK", "Responsable Stock"),
                            ("MAGASINIER", "Magasinier"),
                            ("ACHETEUR", "Acheteur"),
                            ("CONSULTANT", "Consultant (Lecture seule)"),
                        ],
                        default="MAGASINIER",
                        max_length=30,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="utilisateurs/photos/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Service / Département",
                    ),
                ),
                (
                    "date_derniere_connexion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière connexion"
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Compte actif"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ParametreApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(max_length=100, unique=True, verbose_name="Clé"),
                ),
                ("valeur", models.TextField(verbose_name="Valeur")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type_valeur",
                    models.CharField(
                        choices=[
                            ("str", "Texte"),
                            ("int", "Entier"),
                            ("float", "Décimal"),
                            ("bool", "Booléen"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        max_length=20,
                        verbose_name="Type de valeur",
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre",
                "verbose_name_plural": "Paramètres de l'application",
                "ordering": ["cle"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("STOCK", "Alerte stock"),
                            ("PEREMPTION", "Péremption proche"),
                            ("COMMANDE", "Commande en attente"),
                            ("SYSTEME", "Système"),
                            ("INFO", "Information"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("HAUTE", "Haute"),
                            ("NORMALE", "Normale"),
                            ("BASSE", "Basse"),
                        ],
                        default="NORMALE",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                ("lue", models.BooleanField(default=False, verbose_name="Lue")),
                (
                    "date_envoi",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "date_lecture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "lien",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Lien associé",
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="JournalActivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("EXPORT", "Export"),
                            ("PRINT", "Impression"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "modele",
                    models.CharField(max_length=100, verbose_name="Modèle concerné"),
                ),
                (
                    "objet_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID de l'objet",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "date_action",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date et heure"
                    ),
                ),
                (
                    "donnees_avant",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données avant modification"
                    ),
                ),
                (
                    "donnees_apres",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données après modification"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'activité",
                "verbose_name_plural": "Journal des activités",
                "ordering": ["-date_action"],
            },
        ),
    ]
