# Generated by Django 4.2.21 on 2026-04-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalactivite",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("INFO", "Information"),
                    ("WARNING", "Avertissement"),
                    ("ERROR", "Erreur"),
                ],
                default="INFO",
                max_length=10,
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterField(
            model_name="journalactivite",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Création"),
                    ("UPDATE", "Modification"),
                    ("DELETE", "Suppression"),
                    ("LOGIN", "Connexion"),
                    ("LOGOUT", "Déconnexion"),
                    ("EXPORT", "Export"),
                    ("PRINT", "Impression"),
                    ("VALIDATION", "Validation"),
                    ("REJET", "Rejet"),
                    ("ACTIVATION", "Activation"),
                    ("DESACTIVATION", "Désactivation"),
                ],
                max_length=20,
                verbose_name="Action",
            ),
        ),
    ]
