# Generated by Django 4.2.21 on 2026-04-11 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneStockage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Code zone"
                    ),
                ),
                ("libelle", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "type_zone",
                    models.CharField(
                        choices=[
                            ("AMBIANT", "Température ambiante"),
                            ("REFRIGERE", "Zone réfrigérée (2-8°C)"),
                            ("CONGELATION", "Zone de congélation"),
                            ("QUARANTAINE", "Zone de quarantaine"),
                            ("RECEPTION", "Zone de réception"),
                            ("EXPEDITION", "Zone d'expédition"),
                            ("PF", "Produits finis"),
                            ("MP", "Matières premières"),
                        ],
                        default="AMBIANT",
                        max_length=20,
                        verbose_name="Type de zone",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#e9ecef", max_length=7, verbose_name="Couleur (hex)"
                    ),
                ),
                ("position_x", models.FloatField(default=0, verbose_name="Position X")),
                ("position_y", models.FloatField(default=0, verbose_name="Position Y")),
                ("largeur", models.FloatField(default=100, verbose_name="Largeur")),
                ("hauteur", models.FloatField(default=100, verbose_name="Hauteur")),
                (
                    "temperature_min",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "temperature_max",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "capacite_totale",
                    models.FloatField(default=0, verbose_name="Capacité totale (m³)"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone de stockage",
                "verbose_name_plural": "Zones de stockage",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Rayon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("code", models.CharField(max_length=10, verbose_name="Code rayon")),
                ("libelle", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "orientation",
                    models.CharField(
                        choices=[("H", "Horizontal"), ("V", "Vertical")],
                        default="V",
                        max_length=10,
                        verbose_name="Orientation",
                    ),
                ),
                (
                    "nombre_niveaux",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Nombre de niveaux"
                    ),
                ),
                (
                    "nombre_colonnes",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Nombre de colonnes"
                    ),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("largeur", models.FloatField(default=50)),
                ("hauteur", models.FloatField(default=20)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rayons",
                        to="magasin.zonestockage",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rayon",
                "verbose_name_plural": "Rayons",
                "ordering": ["zone", "code"],
                "unique_together": {("zone", "code")},
            },
        ),
        migrations.CreateModel(
            name="PlanMagasin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        default="Plan principal",
                        max_length=100,
                        verbose_name="Nom du plan",
                    ),
                ),
                (
                    "largeur_totale",
                    models.FloatField(
                        default=1000, verbose_name="Largeur totale (pixels)"
                    ),
                ),
                (
                    "hauteur_totale",
                    models.FloatField(
                        default=600, verbose_name="Hauteur totale (pixels)"
                    ),
                ),
                (
                    "echelle",
                    models.FloatField(
                        default=1.0, verbose_name="Échelle (pixels/mètre)"
                    ),
                ),
                (
                    "image_fond",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="magasin/plans/",
                        verbose_name="Image de fond du plan",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "config_affichage",
                    models.JSONField(
                        default=dict,
                        help_text="Paramètres de couleurs, légendes, etc.",
                        verbose_name="Configuration d'affichage JSON",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan du magasin",
                "verbose_name_plural": "Plans du magasin",
            },
        ),
        migrations.CreateModel(
            name="Emplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "code",
                    models.CharField(
                        help_text="Ex: A-R1-N2-C05",
                        max_length=20,
                        unique=True,
                        verbose_name="Code emplacement",
                    ),
                ),
                (
                    "niveau",
                    models.PositiveSmallIntegerField(
                        help_text="1 = niveau bas, 5 = niveau haut",
                        verbose_name="Niveau",
                    ),
                ),
                ("colonne", models.PositiveSmallIntegerField(verbose_name="Colonne")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("LIBRE", "Libre"),
                            ("OCCUPE", "Occupé"),
                            ("RESERVE", "Réservé"),
                            ("BLOQUE", "Bloqué (maintenance)"),
                            ("QUARANTAINE", "Quarantaine"),
                        ],
                        default="LIBRE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "capacite_poids_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacité poids max (kg)",
                    ),
                ),
                (
                    "capacite_volume_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacité volume max (m³)",
                    ),
                ),
                (
                    "type_produit_autorise",
                    models.CharField(
                        choices=[
                            ("TOUS", "Tous types"),
                            ("AMBIANT", "Température ambiante"),
                            ("REFRIGERE", "Réfrigéré"),
                            ("DANGEREUX", "Produits dangereux"),
                        ],
                        default="TOUS",
                        max_length=20,
                        verbose_name="Type de produit autorisé",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="Notes"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "rayon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emplacements",
                        to="magasin.rayon",
                        verbose_name="Rayon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emplacement",
                "verbose_name_plural": "Emplacements",
                "ordering": ["rayon", "niveau", "colonne"],
                "indexes": [
                    models.Index(fields=["code"], name="magasin_emp_code_362f44_idx"),
                    models.Index(
                        fields=["statut"], name="magasin_emp_statut_98eb14_idx"
                    ),
                ],
            },
        ),
    ]
