# Generated by Django 4.2.21 on 2026-04-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magasin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emplacement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("LIBRE", "Libre"),
                    ("OCCUPE", "Occupé"),
                    ("RESERVE", "Réservé"),
                    ("BLOQUE", "Bloqué (maintenance)"),
                    ("QUARANTAINE", "Quarantaine"),
                    ("SATURE", "Saturé"),
                ],
                default="LIBRE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
