# Generated by Django 4.2.21 on 2026-04-26 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("produits", "0005_fournisseur_statut"),
        ("magasin", "0002_alter_emplacement_statut"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zonestockage",
            options={
                "ordering": ["ordre", "code"],
                "verbose_name": "Zone de stockage",
                "verbose_name_plural": "Zones de stockage",
            },
        ),
        migrations.AddField(
            model_name="rayon",
            name="actif",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="rayon",
            name="capacite_max",
            field=models.FloatField(default=0, verbose_name="Capacité max"),
        ),
        migrations.AddField(
            model_name="rayon",
            name="couleur",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="Couleur"
            ),
        ),
        migrations.AddField(
            model_name="rayon",
            name="nom",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom du rayon"
            ),
        ),
        migrations.AddField(
            model_name="rayon",
            name="statut",
            field=models.CharField(
                choices=[
                    ("ACTIF", "Actif"),
                    ("SATURE", "Saturé"),
                    ("BLOQUE", "Bloqué"),
                    ("MAINTENANCE", "En maintenance"),
                ],
                default="ACTIF",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="rayon",
            name="type_stock",
            field=models.CharField(
                choices=[
                    ("MATIERE_PREMIERE", "Matières Premières"),
                    ("PRODUIT_FINI", "Produits Finis"),
                    ("MIXTE", "Mixte"),
                ],
                default="MIXTE",
                max_length=20,
                verbose_name="Type de stock",
            ),
        ),
        migrations.AddField(
            model_name="zonestockage",
            name="actif",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="zonestockage",
            name="humidite_max",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="zonestockage",
            name="humidite_min",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="zonestockage",
            name="nom",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom de la zone"
            ),
        ),
        migrations.AddField(
            model_name="zonestockage",
            name="ordre",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AlterField(
            model_name="zonestockage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description détaillée"),
        ),
        migrations.AlterField(
            model_name="zonestockage",
            name="libelle",
            field=models.CharField(
                max_length=100, verbose_name="Libellé / Description courte"
            ),
        ),
        migrations.AlterField(
            model_name="zonestockage",
            name="type_zone",
            field=models.CharField(
                choices=[
                    ("SECHE", "Zone sèche"),
                    ("FROIDE", "Zone froide (2-8°C)"),
                    ("TEMPEREE", "Température ambiante (15-25°C)"),
                    ("QUARANTAINE", "Zone de quarantaine"),
                    ("RECEPTION", "Zone de réception"),
                    ("EXPEDITION", "Zone d'expédition"),
                    ("MATIERES_PREMIERES", "Matières premières"),
                    ("PRODUITS_FINIS", "Produits finis"),
                    ("MIXTE", "Zone mixte"),
                ],
                default="SECHE",
                max_length=20,
                verbose_name="Type de zone",
            ),
        ),
        migrations.CreateModel(
            name="NiveauRayon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "numero",
                    models.PositiveSmallIntegerField(verbose_name="Numéro du niveau"),
                ),
                (
                    "libelle",
                    models.CharField(blank=True, max_length=50, verbose_name="Libellé"),
                ),
                (
                    "capacite_max",
                    models.FloatField(default=0, verbose_name="Capacité maximale"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "rayon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveaux",
                        to="magasin.rayon",
                        verbose_name="Rayon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau de rayon",
                "verbose_name_plural": "Niveaux de rayons",
                "ordering": ["rayon", "numero"],
                "unique_together": {("rayon", "numero")},
            },
        ),
        migrations.CreateModel(
            name="AffectationStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "quantite_affectee",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="Quantité affectée",
                    ),
                ),
                (
                    "capacite_reservee",
                    models.FloatField(default=0, verbose_name="Capacité réservée"),
                ),
                (
                    "date_affectation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'affectation"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "matiere_premiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations_magasin",
                        to="produits.matierepremiere",
                        verbose_name="Matière Première",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to="magasin.niveaurayon",
                        verbose_name="Niveau de rayon",
                    ),
                ),
                (
                    "produit_fini",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations_magasin",
                        to="produits.produitfini",
                        verbose_name="Produit Fini",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation de stock",
                "verbose_name_plural": "Affectations de stock",
            },
        ),
    ]
