# Generated by Django 4.2.21 on 2026-04-26 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("magasin", "0003_alter_zonestockage_options_rayon_actif_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelimitationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "nom",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la délimitation"
                    ),
                ),
                (
                    "type_delimitation",
                    models.CharField(
                        choices=[
                            ("COULOIR", "Couloir"),
                            ("SEPARATION", "Séparation physique"),
                            ("PERIMETRE", "Périmètre fonctionnel"),
                            ("SECURITE", "Zone de sécurité"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("largeur", models.FloatField(default=100)),
                ("hauteur", models.FloatField(default=100)),
                (
                    "couleur",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="Couleur"
                    ),
                ),
                (
                    "epaisseur",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Épaisseur (px)"
                    ),
                ),
                (
                    "style_trait",
                    models.CharField(
                        choices=[
                            ("PLEIN", "Trait plein"),
                            ("POINTILLE", "Trait pointillé"),
                        ],
                        default="PLEIN",
                        max_length=10,
                        verbose_name="Style de trait",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délimitation de plan",
                "verbose_name_plural": "Délimitations de plan",
            },
        ),
    ]
