# Generated by Django 4.2.21 on 2026-04-11 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPISnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "nb_references_actives",
                    models.IntegerField(default=0, verbose_name="Références actives"),
                ),
                (
                    "nb_ruptures",
                    models.IntegerField(default=0, verbose_name="Ruptures de stock"),
                ),
                (
                    "nb_alertes",
                    models.IntegerField(default=0, verbose_name="Alertes stock"),
                ),
                (
                    "nb_peremptions_proches",
                    models.IntegerField(
                        default=0, verbose_name="Péremptions < 90 jours"
                    ),
                ),
                (
                    "valeur_stock_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Valeur totale stock (DH)",
                    ),
                ),
                ("nb_commandes_en_cours", models.IntegerField(default=0)),
                (
                    "montant_commandes_en_cours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "taux_service",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de service (%)",
                    ),
                ),
                (
                    "taux_rotation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de rotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot KPI",
                "verbose_name_plural": "Snapshots KPI",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RapportSauvegarde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom du rapport"),
                ),
                (
                    "type_rapport",
                    models.CharField(
                        choices=[
                            ("STOCK", "Rapport de stock"),
                            ("MVTS", "Rapport des mouvements"),
                            ("VALOR", "Valorisation du stock"),
                            ("PEREMS", "Alertes péremptions"),
                            ("CMDS", "Rapport des commandes"),
                            ("ABC", "Analyse ABC"),
                            ("KPI", "Indicateurs KPI"),
                        ],
                        max_length=10,
                        verbose_name="Type de rapport",
                    ),
                ),
                (
                    "parametres",
                    models.JSONField(
                        default=dict, verbose_name="Paramètres de génération"
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="rapports/",
                        verbose_name="Fichier généré",
                    ),
                ),
                (
                    "date_generation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de génération"
                    ),
                ),
                (
                    "periode_debut",
                    models.DateField(blank=True, null=True, verbose_name="Période du"),
                ),
                (
                    "periode_fin",
                    models.DateField(blank=True, null=True, verbose_name="Au"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Généré par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport sauvegardé",
                "verbose_name_plural": "Rapports sauvegardés",
                "ordering": ["-date_generation"],
            },
        ),
    ]
