# Generated by Django 4.2.21 on 2026-04-11 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommandeAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° de commande"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDATION", "En attente de validation"),
                            ("VALIDE", "Validée"),
                            ("ENVOYE", "Envoyée au fournisseur"),
                            ("PARTIEL", "Partiellement réceptionnée"),
                            ("RECU", "Totalement réceptionnée"),
                            ("ANNULE", "Annulée"),
                            ("CLOTURE", "Clôturée"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "type_commande",
                    models.CharField(
                        choices=[
                            ("NORMALE", "Commande normale"),
                            ("URGENTE", "Commande urgente"),
                            ("AUTO", "Générée automatiquement"),
                            ("MRP", "Ordre MRP"),
                        ],
                        default="NORMALE",
                        max_length=20,
                        verbose_name="Type de commande",
                    ),
                ),
                (
                    "methode_declenchement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REAPPRO_FIXE", "Réapprovisionnement à quantité fixe"),
                            ("POINT_COMMANDE", "Point de commande (ROP)"),
                            ("RECOMPLETEMENT", "Récompletement périodique (S,T)"),
                            ("MRP", "MRP — Calcul des besoins en matières"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Méthode de déclenchement",
                    ),
                ),
                (
                    "date_commande",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de commande",
                    ),
                ),
                (
                    "date_livraison_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison prévue"
                    ),
                ),
                (
                    "date_livraison_reelle",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison réelle"
                    ),
                ),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Montant HT (DH)",
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Montant TVA (DH)",
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Montant TTC (DH)",
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "conditions_paiement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Conditions de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande d'achat",
                "verbose_name_plural": "Commandes d'achat",
                "ordering": ["-date_commande"],
            },
        ),
        migrations.CreateModel(
            name="LigneCommandeAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_commandee",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Quantité commandée",
                    ),
                ),
                (
                    "quantite_recue",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Quantité reçue",
                    ),
                ),
                (
                    "prix_unitaire_ht",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Prix unitaire HT"
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "date_livraison_souhaitee",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de livraison souhaitée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
            },
        ),
        migrations.CreateModel(
            name="LigneMRP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semaine", models.PositiveSmallIntegerField(verbose_name="Semaine")),
                ("annee", models.PositiveSmallIntegerField(verbose_name="Année")),
                (
                    "besoin_brut",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Besoin brut (BB)",
                    ),
                ),
                (
                    "reception_programmee",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Réception programmée (RP)",
                    ),
                ),
                (
                    "stock_disponible",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock disponible projeté",
                    ),
                ),
                (
                    "besoin_net",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Besoin net (BN)",
                    ),
                ),
                (
                    "ordre_propose",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Ordre proposé (OP)",
                    ),
                ),
                (
                    "ordre_lance",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Ordre lancé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne MRP",
                "verbose_name_plural": "Lignes MRP",
                "ordering": ["annee", "semaine"],
            },
        ),
        migrations.CreateModel(
            name="ParametreAppro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("REAPPRO_FIXE", "Réapprovisionnement à quantité fixe"),
                            ("POINT_COMMANDE", "Point de commande (ROP)"),
                            ("RECOMPLETEMENT", "Récompletement périodique (S,T)"),
                            ("MRP", "MRP — Calcul des besoins en matières"),
                        ],
                        max_length=20,
                        verbose_name="Méthode d'approvisionnement",
                    ),
                ),
                (
                    "consommation_journaliere_moyenne",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="Consommation journalière moyenne (CJM)",
                    ),
                ),
                (
                    "ecart_type_consommation",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="Écart-type de la consommation",
                    ),
                ),
                (
                    "delai_reappro_jours",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Délai de réapprovisionnement (jours)"
                    ),
                ),
                (
                    "niveau_service",
                    models.DecimalField(
                        decimal_places=2,
                        default=95.0,
                        max_digits=5,
                        verbose_name="Niveau de service cible (%)",
                    ),
                ),
                (
                    "cout_possession",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        verbose_name="Coût de possession (% valeur/an)",
                    ),
                ),
                (
                    "cout_passation",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=10,
                        verbose_name="Coût de passation de commande (DH)",
                    ),
                ),
                (
                    "quantite_commande_fixe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="[FIXE] Quantité de commande fixe Q",
                    ),
                ),
                (
                    "periodicite_commande",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="[FIXE] Périodicité de commande (jours)",
                    ),
                ),
                (
                    "date_prochaine_commande",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="[FIXE] Date de prochaine commande",
                    ),
                ),
                (
                    "point_commande_calcule",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="[ROP] Point de commande calculé",
                    ),
                ),
                (
                    "stock_securite_calcule",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="[ROP] Stock de sécurité calculé",
                    ),
                ),
                (
                    "qec_calcule",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="[ROP] QEC calculée (Wilson)",
                    ),
                ),
                (
                    "stock_cible",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="[S,T] Stock cible S",
                    ),
                ),
                (
                    "periode_revision",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="[S,T] Période de révision T (jours)",
                    ),
                ),
                (
                    "nomenclature_coefficient",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        max_digits=10,
                        verbose_name="[MRP] Coefficient de nomenclature",
                    ),
                ),
                (
                    "lot_multiple",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="[MRP] Lot multiple / Taille de lot",
                    ),
                ),
                (
                    "horizon_planification",
                    models.PositiveIntegerField(
                        default=12,
                        verbose_name="[MRP] Horizon de planification (semaines)",
                    ),
                ),
                (
                    "date_derniere_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre d'approvisionnement",
                "verbose_name_plural": "Paramètres d'approvisionnement",
            },
        ),
        migrations.CreateModel(
            name="PlanMRP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° plan MRP"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("CALCUL", "Calcul en cours"),
                            ("CALCULE", "Calculé"),
                            ("APPROUVE", "Approuvé"),
                            ("EN_COURS", "En cours d'exécution"),
                            ("TERMINE", "Terminé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="CALCUL",
                        max_length=20,
                    ),
                ),
                (
                    "horizon_semaines",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Horizon (semaines)"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Plan MRP",
                "verbose_name_plural": "Plans MRP",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="SuggestionAppro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("REAPPRO_FIXE", "Réapprovisionnement à quantité fixe"),
                            ("POINT_COMMANDE", "Point de commande (ROP)"),
                            ("RECOMPLETEMENT", "Récompletement périodique (S,T)"),
                            ("MRP", "MRP — Calcul des besoins en matières"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de calcul",
                    ),
                ),
                (
                    "quantite_suggeree",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Quantité suggérée",
                    ),
                ),
                (
                    "date_suggestion",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de suggestion",
                    ),
                ),
                (
                    "date_commande_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de commande prévue"
                    ),
                ),
                (
                    "date_livraison_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison prévue"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("NOUVELLE", "Nouvelle"),
                            ("ACCEPTEE", "Acceptée"),
                            ("REJETEE", "Rejetée"),
                            ("TRANSFORMEE", "Transformée en commande"),
                        ],
                        default="NOUVELLE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "stock_au_moment",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock au moment du calcul",
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, verbose_name="Justification du calcul"
                    ),
                ),
                ("urgente", models.BooleanField(default=False, verbose_name="Urgente")),
                (
                    "commande_generee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions_origine",
                        to="approvisionnement.commandeachat",
                        verbose_name="Commande générée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suggestion d'approvisionnement",
                "verbose_name_plural": "Suggestions d'approvisionnement",
                "ordering": ["-date_suggestion", "-urgente"],
            },
        ),
    ]
