# Generated by Django 4.2.21 on 2026-04-11 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Générée automatiquement : BC-YYYY-XXXX",
                        max_length=20,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "quantite_commandee",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantité commandée",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix unitaire (DH)",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant total (DH)",
                    ),
                ),
                (
                    "methode_declenchement",
                    models.CharField(
                        choices=[
                            ("REAPPRO_FIXE", "Réappro fixe"),
                            ("POINT_COMMANDE", "Point de commande"),
                            ("RECOMPLETEMENT", "Récompletement"),
                            ("MRP", "MRP"),
                            ("MANUEL", "Manuel"),
                        ],
                        default="MANUEL",
                        max_length=20,
                        verbose_name="Méthode de déclenchement",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("ENVOYE", "Envoyé"),
                            ("CONFIRME", "Confirmé"),
                            ("RECU", "Reçu"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "date_reception_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Réception prévue"
                    ),
                ),
                (
                    "date_reception_reelle",
                    models.DateField(
                        blank=True, null=True, verbose_name="Réception réelle"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Bon de commande",
                "verbose_name_plural": "Bons de commande",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PlanMRP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periode",
                    models.DateField(
                        help_text="Date de début de la période de planification",
                        verbose_name="Période (début de semaine / mois)",
                    ),
                ),
                (
                    "besoin_brut",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Besoin brut",
                    ),
                ),
                (
                    "stock_debut_periode",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock en début de période",
                    ),
                ),
                (
                    "besoin_net",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="max(0, Besoin brut − Stock début − Réceptions prévues)",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Besoin net",
                    ),
                ),
                (
                    "quantite_proposee",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantité d'ordre proposée",
                    ),
                ),
                (
                    "stock_fin_periode",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        verbose_name="Stock en fin de période",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("CALCULE", "Calculé"),
                            ("CONFIRME", "Confirmé"),
                            ("LANCE", "Lancé"),
                        ],
                        default="CALCULE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans_mrp",
                        to="produits.matierepremiere",
                        verbose_name="Matière première",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan MRP",
                "verbose_name_plural": "Plans MRP",
                "ordering": ["matiere", "periode"],
            },
        ),
    ]
