# Generated by Django 4.2.21 on 2026-04-11 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produits", "0001_initial"),
        ("approvisionnement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionappro",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="suggestionappro",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produits.fournisseur",
                verbose_name="Fournisseur suggéré",
            ),
        ),
        migrations.AddField(
            model_name="suggestionappro",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="suggestionappro",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions",
                to="produits.produit",
                verbose_name="Produit",
            ),
        ),
        migrations.AddField(
            model_name="planmrp",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="planmrp",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="parametreappro",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="parametreappro",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="parametreappro",
            name="produit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parametre_appro",
                to="produits.produit",
                verbose_name="Produit",
            ),
        ),
        migrations.AddField(
            model_name="lignemrp",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="approvisionnement.planmrp",
                verbose_name="Plan MRP",
            ),
        ),
        migrations.AddField(
            model_name="lignemrp",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes_mrp",
                to="produits.produit",
                verbose_name="Produit",
            ),
        ),
        migrations.AddField(
            model_name="lignecommandeachat",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="approvisionnement.commandeachat",
                verbose_name="Commande",
            ),
        ),
        migrations.AddField(
            model_name="lignecommandeachat",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande",
                to="produits.produit",
                verbose_name="Produit",
            ),
        ),
        migrations.AddField(
            model_name="lignecommandeachat",
            name="unite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="produits.unitemesure",
                verbose_name="Unité",
            ),
        ),
        migrations.AddField(
            model_name="commandeachat",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="commandeachat",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commandes",
                to="produits.fournisseur",
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="commandeachat",
            name="modifie_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="commandeachat",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes_validees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validé par",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lignemrp",
            unique_together={("plan", "produit", "semaine", "annee")},
        ),
        migrations.AddIndex(
            model_name="commandeachat",
            index=models.Index(fields=["statut"], name="approvision_statut_4ee3a3_idx"),
        ),
        migrations.AddIndex(
            model_name="commandeachat",
            index=models.Index(
                fields=["fournisseur", "statut"], name="approvision_fournis_4d1d04_idx"
            ),
        ),
    ]
