# Generated by Django 4.2.21 on 2026-04-11 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("approvisionnement", "0001_initial"),
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boncommande",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bons_commande_crees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="boncommande",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bons_commande",
                to="produits.fournisseur",
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="boncommande",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bons_commande",
                to="produits.matierepremiere",
                verbose_name="Matière première",
            ),
        ),
        migrations.AddIndex(
            model_name="planmrp",
            index=models.Index(
                fields=["matiere", "periode"], name="approvision_matiere_632eb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planmrp",
            index=models.Index(fields=["statut"], name="approvision_statut_557589_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="planmrp",
            unique_together={("matiere", "periode")},
        ),
        migrations.AddIndex(
            model_name="boncommande",
            index=models.Index(fields=["statut"], name="approvision_statut_52c406_idx"),
        ),
        migrations.AddIndex(
            model_name="boncommande",
            index=models.Index(
                fields=["reference"], name="approvision_referen_b970bd_idx"
            ),
        ),
    ]
