# Generated by Django 4.2.21 on 2026-04-20 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0001_initial"),
        ("approvisionnement", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropositionCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "methode",
                    models.CharField(
                        help_text="Copie de matiere.methode_approvisionnement au moment du calcul",
                        max_length=20,
                        verbose_name="Méthode (héritée)",
                    ),
                ),
                (
                    "quantite_proposee",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantité proposée",
                    ),
                ),
                (
                    "quantite_validee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Modifiable par l'acheteur avant conversion en BC",
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantité validée",
                    ),
                ),
                (
                    "detail_calcul",
                    models.JSONField(
                        default=dict,
                        help_text="Stocke les paramètres utilisés: stock, ROP, QEC, période...",
                        verbose_name="Détail du calcul",
                    ),
                ),
                (
                    "urgence",
                    models.BooleanField(
                        default=False,
                        help_text="True si stock en rupture ou sous stock de sécurité",
                        verbose_name="Urgente",
                    ),
                ),
                (
                    "date_generation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de génération"
                    ),
                ),
                (
                    "date_besoin",
                    models.DateField(
                        blank=True,
                        help_text="Date limite avant rupture estimée",
                        null=True,
                        verbose_name="Date de besoin",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PROPOSEE", "Proposée"),
                            ("VALIDEE", "Validée"),
                            ("REJETEE", "Rejetée"),
                            ("CONVERTIE", "Convertie en BC"),
                        ],
                        default="PROPOSEE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "note_acheteur",
                    models.TextField(blank=True, verbose_name="Note acheteur"),
                ),
                (
                    "bon_commande",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposition_origine",
                        to="approvisionnement.boncommande",
                        verbose_name="Bon de commande généré",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions",
                        to="produits.matierepremiere",
                        verbose_name="Matière première",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposition de commande",
                "verbose_name_plural": "Propositions de commande",
                "ordering": ["-urgence", "date_besoin"],
                "indexes": [
                    models.Index(
                        fields=["statut"], name="approvision_statut_d50866_idx"
                    ),
                    models.Index(
                        fields=["matiere", "statut"],
                        name="approvision_matiere_936a01_idx",
                    ),
                ],
            },
        ),
    ]
