# Generated by Django 4.2.21 on 2026-04-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0007_refactor_nomenclature"),
        ("approvisionnement", "0003_propositioncommande"),
    ]

    operations = [
        migrations.AddField(
            model_name="propositioncommande",
            name="cle_deduplication",
            field=models.CharField(
                blank=True,
                help_text="Format: [matiere_id]-[methode]-[periode] pour éviter les doublons",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Clé de déduplication",
            ),
        ),
        migrations.AddField(
            model_name="propositioncommande",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propositions",
                to="produits.fournisseur",
                verbose_name="Fournisseur proposé",
            ),
        ),
        migrations.AlterField(
            model_name="propositioncommande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("VALIDEE", "Validée"),
                    ("REJETEE", "Rejetée"),
                    ("CONVERTIE", "Convertie en BC"),
                    ("EXPIREE", "Expirée"),
                ],
                default="EN_ATTENTE",
                max_length=15,
                verbose_name="Statut",
            ),
        ),
    ]
