# Generated by Django 4.2.21 on 2026-04-11 13:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produits", "0001_initial"),
        ("magasin", "0001_initial"),
        ("approvisionnement", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° inventaire"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                (
                    "type_inventaire",
                    models.CharField(
                        choices=[
                            ("COMPLET", "Inventaire complet"),
                            ("PARTIEL", "Inventaire partiel"),
                            ("TOURNANT", "Inventaire tournant"),
                        ],
                        default="COMPLET",
                        max_length=20,
                        verbose_name="Type d'inventaire",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventaires",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventaire",
                "verbose_name_plural": "Inventaires",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="BonSortie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° bon de sortie"
                    ),
                ),
                (
                    "service_demandeur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Service demandeur"
                    ),
                ),
                (
                    "date_demande",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de demande",
                    ),
                ),
                (
                    "date_livraison_souhaitee",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de livraison souhaitée",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE", "En attente de validation"),
                            ("VALIDE", "Validé"),
                            ("PREPARE", "Préparé"),
                            ("EXPEDIE", "Expédié / Livré"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Motif de sortie"
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bons_sortie_demandes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_sortie_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de sortie",
                "verbose_name_plural": "Bons de sortie",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="BonEntree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° bon d'entrée"
                    ),
                ),
                (
                    "date_reception",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de réception",
                    ),
                ),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Réf. fournisseur"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("PARTIELLE", "Réception partielle"),
                            ("TOTALE", "Réception totale"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date validation"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_entree",
                        to="approvisionnement.commandeachat",
                        verbose_name="Bon de commande associé",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bons_entree",
                        to="produits.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_entree_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon d'entrée",
                "verbose_name_plural": "Bons d'entrée",
                "ordering": ["-date_reception"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "numero",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° de mouvement"
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée en stock"),
                            ("SORTIE", "Sortie de stock"),
                            ("AJUST_POS", "Ajustement positif (inventaire)"),
                            ("AJUST_NEG", "Ajustement négatif (inventaire)"),
                            ("TRANSFERT", "Transfert inter-emplacements"),
                            ("RETOUR", "Retour fournisseur"),
                            ("PERTE", "Perte / Destruction"),
                            ("PEREMPTION", "Mise au rebut (péremption)"),
                        ],
                        max_length=20,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE", "En attente de validation"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.001)],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="Prix unitaire (DH)",
                    ),
                ),
                (
                    "stock_avant",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock avant mouvement",
                    ),
                ),
                (
                    "stock_apres",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock après mouvement",
                    ),
                ),
                (
                    "date_mouvement",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date du mouvement",
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "reference_document",
                    models.CharField(
                        blank=True,
                        help_text="N° BL, N° BC, N° facture, etc.",
                        max_length=100,
                        verbose_name="Référence document",
                    ),
                ),
                (
                    "bon_livraison",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N° Bon de livraison"
                    ),
                ),
                (
                    "motif",
                    models.TextField(blank=True, verbose_name="Motif / Observation"),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements",
                        to="approvisionnement.commandeachat",
                        verbose_name="Commande associée",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "emplacement_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_entree",
                        to="magasin.emplacement",
                        verbose_name="Emplacement destination",
                    ),
                ),
                (
                    "emplacement_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_sortie",
                        to="magasin.emplacement",
                        verbose_name="Emplacement source",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements",
                        to="produits.lotproduit",
                        verbose_name="Lot",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="produits.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "unite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produits.unitemesure",
                        verbose_name="Unité",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-date_mouvement"],
                "indexes": [
                    models.Index(
                        fields=["numero"], name="mouvements__numero_441d4c_idx"
                    ),
                    models.Index(
                        fields=["produit", "date_mouvement"],
                        name="mouvements__produit_e78817_idx",
                    ),
                    models.Index(
                        fields=["type_mouvement", "statut"],
                        name="mouvements__type_mo_05b228_idx",
                    ),
                    models.Index(
                        fields=["date_mouvement"], name="mouvements__date_mo_3f15fd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LigneInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_theorique",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Quantité théorique (système)",
                    ),
                ),
                (
                    "quantite_comptee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Quantité comptée",
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        decimal_places=3, default=0, max_digits=12, verbose_name="Écart"
                    ),
                ),
                ("observations", models.CharField(blank=True, max_length=200)),
                (
                    "inventaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="mouvements.inventaire",
                        verbose_name="Inventaire",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.lotproduit",
                        verbose_name="Lot",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_inventaire",
                        to="produits.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'inventaire",
                "verbose_name_plural": "Lignes d'inventaire",
                "unique_together": {("inventaire", "produit", "lot")},
            },
        ),
    ]
