# Generated by Django 4.2.21 on 2026-04-11 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produits", "0001_initial"),
        ("approvisionnement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[("ENTREE", "Entrée"), ("SORTIE", "Sortie")],
                        max_length=10,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantité mouvementée",
                    ),
                ),
                (
                    "quantite_avant",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Snapshot du stock juste avant ce mouvement",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock avant mouvement",
                    ),
                ),
                (
                    "quantite_apres",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Calculé automatiquement lors de la validation",
                        max_digits=14,
                        verbose_name="Stock après mouvement",
                    ),
                ),
                (
                    "date_mouvement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date du mouvement"
                    ),
                ),
                (
                    "motif",
                    models.CharField(blank=True, max_length=255, verbose_name="Motif"),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de lot"
                    ),
                ),
                (
                    "date_peremption",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de péremption du lot"
                    ),
                ),
                (
                    "bon_commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements",
                        to="approvisionnement.boncommande",
                        verbose_name="Bon de commande associé",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="produits.matierepremiere",
                        verbose_name="Matière première",
                    ),
                ),
                (
                    "operateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_effectues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opérateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-date_mouvement"],
                "indexes": [
                    models.Index(
                        fields=["matiere", "date_mouvement"],
                        name="mouvements__matiere_561769_idx",
                    ),
                    models.Index(
                        fields=["type_mouvement"], name="mouvements__type_mo_f17512_idx"
                    ),
                    models.Index(
                        fields=["numero_lot"], name="mouvements__numero__f5cea0_idx"
                    ),
                ],
            },
        ),
    ]
