# Generated by Django 4.2.21 on 2026-04-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0003_add_produit_fini"),
        ("mouvements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouvementstock",
            name="produit_fini",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mouvements",
                to="produits.produitfini",
                verbose_name="Produit fini",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="type_stock",
            field=models.CharField(
                choices=[("MP", "Matière première"), ("PF", "Produit fini")],
                default="MP",
                max_length=2,
                verbose_name="Type de stock",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementstock",
            name="matiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mouvements",
                to="produits.matierepremiere",
                verbose_name="Matière première",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["produit_fini", "date_mouvement"],
                name="mouvements__produit_85d3ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(
                fields=["type_stock"], name="mouvements__type_st_52251b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mouvementstock",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("matiere__isnull", False), ("produit_fini__isnull", True)
                    ),
                    models.Q(
                        ("matiere__isnull", True), ("produit_fini__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="mouvementstock_matiere_ou_produit_fini",
            ),
        ),
    ]
