# Generated by Django 4.2.21 on 2026-04-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouvements", "0002_add_produit_fini"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementstock",
            name="type_mouvement",
            field=models.CharField(
                choices=[
                    ("ENTREE", "Entrée"),
                    ("SORTIE", "Sortie"),
                    ("AJUSTEMENT", "Ajustement"),
                    ("TRANSFERT", "Transfert"),
                ],
                max_length=10,
                verbose_name="Type de mouvement",
            ),
        ),
    ]
