# Generated by Django 4.2.21 on 2026-04-11 13:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("magasin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "couleur",
                    models.CharField(
                        default="#0d6efd", max_length=7, verbose_name="Couleur (hex)"
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        default="bi-box",
                        max_length=50,
                        verbose_name="Icône Bootstrap",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sous_categories",
                        to="produits.categorieproduit",
                        verbose_name="Catégorie parente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie de produit",
                "verbose_name_plural": "Catégories de produits",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code fournisseur"
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                (
                    "nom_commercial",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom commercial"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("INACTIF", "Inactif"),
                            ("SUSPENDU", "Suspendu"),
                            ("PROSPECT", "Prospect"),
                        ],
                        default="ACTIF",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("adresse", models.TextField(verbose_name="Adresse")),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code postal"
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Maroc", max_length=50, verbose_name="Pays"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="Fax"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "contact_nom",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom du contact"
                    ),
                ),
                (
                    "contact_telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone contact"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email contact"
                    ),
                ),
                (
                    "contact_poste",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Poste contact"
                    ),
                ),
                (
                    "ice",
                    models.CharField(blank=True, max_length=15, verbose_name="ICE"),
                ),
                (
                    "if_numero",
                    models.CharField(blank=True, max_length=20, verbose_name="N° IF"),
                ),
                ("rc", models.CharField(blank=True, max_length=20, verbose_name="RC")),
                (
                    "delai_livraison_moyen",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Délai de livraison moyen (jours)"
                    ),
                ),
                (
                    "conditions_paiement",
                    models.CharField(
                        default="30 jours net",
                        max_length=100,
                        verbose_name="Conditions de paiement",
                    ),
                ),
                (
                    "remise_habituelle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Remise habituelle (%)",
                    ),
                ),
                (
                    "note_evaluation",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Évaluation (1-5)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["raison_sociale"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Code produit"
                    ),
                ),
                (
                    "code_barre",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Code barre",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=200, verbose_name="Désignation"),
                ),
                (
                    "designation_arabe",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Désignation en arabe"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="produits/photos/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("INACTIF", "Inactif"),
                            ("ARCHIVE", "Archivé"),
                            ("DISCONTINUE", "Discontinué"),
                        ],
                        default="ACTIF",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "classe_abc",
                    models.CharField(
                        choices=[
                            ("A", "Classe A (priorité haute)"),
                            ("B", "Classe B (priorité moyenne)"),
                            ("C", "Classe C (priorité basse)"),
                        ],
                        default="B",
                        max_length=1,
                        verbose_name="Classe ABC",
                    ),
                ),
                (
                    "coefficient_conversion",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Nombre d'unités de stock par unité d'achat",
                        max_digits=10,
                        verbose_name="Coefficient de conversion",
                    ),
                ),
                (
                    "stock_actuel",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock actuel",
                    ),
                ),
                (
                    "stock_minimum",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock minimum (seuil d'alerte)",
                    ),
                ),
                (
                    "stock_maximum",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock maximum",
                    ),
                ),
                (
                    "stock_securite",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Stock de sécurité",
                    ),
                ),
                (
                    "point_commande",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Point de commande",
                    ),
                ),
                (
                    "quantite_economique",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Quantité économique de commande (QEC)",
                    ),
                ),
                (
                    "prix_unitaire_achat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Prix unitaire d'achat (DH)",
                    ),
                ),
                (
                    "prix_unitaire_revient",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Prix de revient unitaire (DH)",
                    ),
                ),
                (
                    "tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "type_stockage",
                    models.CharField(
                        choices=[
                            ("AMBIANT", "Température ambiante"),
                            ("REFRIGERE", "Réfrigéré (2-8°C)"),
                            ("CONGELE", "Congelé (< -18°C)"),
                            ("CONTROLE", "Température contrôlée"),
                        ],
                        default="AMBIANT",
                        max_length=20,
                        verbose_name="Conditions de stockage",
                    ),
                ),
                (
                    "temperature_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Température min (°C)",
                    ),
                ),
                (
                    "temperature_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Température max (°C)",
                    ),
                ),
                (
                    "duree_conservation",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Durée de conservation (mois)",
                    ),
                ),
                (
                    "methode_appro",
                    models.CharField(
                        choices=[
                            ("REAPPRO_FIXE", "Réaprovisionnement à quantité fixe"),
                            ("POINT_COMMANDE", "Point de commande (ROP)"),
                            ("RECOMPLETEMENT", "Récompletement périodique"),
                            ("MRP", "MRP — Calcul des besoins"),
                        ],
                        default="POINT_COMMANDE",
                        max_length=30,
                        verbose_name="Méthode d'approvisionnement",
                    ),
                ),
                (
                    "delai_reappro",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Délai de réapprovisionnement (jours)"
                    ),
                ),
                (
                    "periodicite_reappro",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Périodicité de réapprovisionnement (jours)",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produits",
                        to="produits.categorieproduit",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produits",
                        to="magasin.emplacement",
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "fournisseur_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produits_principaux",
                        to="produits.fournisseur",
                        verbose_name="Fournisseur principal",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["designation"],
            },
        ),
        migrations.CreateModel(
            name="UniteMesure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ex: kg, g, L, mL, cp, fl",
                        max_length=10,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("libelle", models.CharField(max_length=50, verbose_name="Libellé")),
                (
                    "libelle_pluriel",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Libellé pluriel"
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("MASSE", "Masse"),
                            ("VOLUME", "Volume"),
                            ("QUANTITE", "Quantité"),
                            ("LONGUEUR", "Longueur"),
                            ("AUTRE", "Autre"),
                        ],
                        default="QUANTITE",
                        max_length=30,
                        verbose_name="Catégorie",
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Unité de mesure",
                "verbose_name_plural": "Unités de mesure",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="TarifFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Référence fournisseur"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Prix unitaire (DH)",
                    ),
                ),
                (
                    "quantite_minimum",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=12,
                        verbose_name="Quantité minimale de commande",
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "date_validite_debut",
                    models.DateField(verbose_name="Valable à partir du"),
                ),
                (
                    "date_validite_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valable jusqu'au"
                    ),
                ),
                (
                    "est_principal",
                    models.BooleanField(default=False, verbose_name="Tarif principal"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="produits.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifs",
                        to="produits.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif fournisseur",
                "verbose_name_plural": "Tarifs fournisseurs",
                "ordering": ["-date_validite_debut"],
            },
        ),
        migrations.AddField(
            model_name="produit",
            name="unite_achat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produits_achat",
                to="produits.unitemesure",
                verbose_name="Unité d'achat",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="unite_stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produits_stock",
                to="produits.unitemesure",
                verbose_name="Unité de stockage",
            ),
        ),
        migrations.CreateModel(
            name="LotProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "numero_lot",
                    models.CharField(max_length=50, verbose_name="Numéro de lot"),
                ),
                (
                    "date_fabrication",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fabrication"
                    ),
                ),
                (
                    "date_peremption",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de péremption"
                    ),
                ),
                (
                    "quantite_initiale",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Quantité initiale",
                    ),
                ),
                (
                    "quantite_restante",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Quantité restante",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("QUARANTAINE", "Quarantaine"),
                            ("LIBERE", "Libéré"),
                            ("REJETE", "Rejeté"),
                            ("EPUISE", "Épuisé"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Origine / Fournisseur"
                    ),
                ),
                (
                    "certificat_analyse",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lots/certificats/",
                        verbose_name="Certificat d'analyse",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="produits.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot de produit",
                "verbose_name_plural": "Lots de produits",
                "ordering": ["date_peremption", "date_fabrication"],
            },
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(fields=["code"], name="produits_pr_code_80c51d_idx"),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["designation"], name="produits_pr_designa_e95e5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(fields=["statut"], name="produits_pr_statut_4f7089_idx"),
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["categorie"], name="produits_pr_categor_b80ae3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lotproduit",
            unique_together={("produit", "numero_lot")},
        ),
    ]
