# Generated by Django 4.2.21 on 2026-04-11 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom / Raison sociale"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Personne de contact"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Maroc", max_length=100, verbose_name="Pays"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="UnitesMesure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                ("symbole", models.CharField(max_length=10, verbose_name="Symbole")),
            ],
            options={
                "verbose_name": "Unité de mesure",
                "verbose_name_plural": "Unités de mesure",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="MatierePremiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Ex : API-001, EXC-042",
                        max_length=30,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("PRINCIPE_ACTIF", "Principe actif"),
                            ("EXCIPIENT", "Excipient"),
                            ("CONDITIONNEMENT", "Conditionnement"),
                        ],
                        default="PRINCIPE_ACTIF",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix unitaire (DH)",
                    ),
                ),
                (
                    "stock_actuel",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock actuel",
                    ),
                ),
                (
                    "stock_minimum",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock minimum",
                    ),
                ),
                (
                    "stock_maximum",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock maximum",
                    ),
                ),
                (
                    "stock_securite",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock de sécurité",
                    ),
                ),
                (
                    "methode_approvisionnement",
                    models.CharField(
                        choices=[
                            ("REAPPRO_FIXE", "Réappro fixe (Q, T)"),
                            ("POINT_COMMANDE", "Point de commande (ROP)"),
                            ("RECOMPLETEMENT", "Récompletement (S, T)"),
                            ("MRP", "MRP"),
                        ],
                        default="POINT_COMMANDE",
                        max_length=20,
                        verbose_name="Méthode d'approvisionnement",
                    ),
                ),
                (
                    "point_commande",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Seuil déclencheur d'une commande (méthode ROP)",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Point de commande (ROP)",
                    ),
                ),
                (
                    "qec",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Calculée par la formule de Wilson : √(2·D·K / (h·Pu))",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="QEC — Quantité économique de commande",
                    ),
                ),
                (
                    "delai_livraison_jours",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="Délai de livraison (jours)"
                    ),
                ),
                (
                    "periode_reappro_jours",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Utilisé pour les méthodes Réappro Fixe et Récompletement",
                        verbose_name="Période de réappro (jours)",
                    ),
                ),
                (
                    "taux_rebut",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Proportion de perte en production (ex : 0.02 = 2 %)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Taux de rebut (MRP)",
                    ),
                ),
                (
                    "zone_stockage",
                    models.CharField(
                        choices=[
                            ("FROIDE", "Zone froide (2 – 8 °C)"),
                            ("TEMPEREE", "Température ambiante (15 – 25 °C)"),
                            ("SECHE", "Zone sèche"),
                        ],
                        default="TEMPEREE",
                        max_length=10,
                        verbose_name="Zone de stockage",
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True,
                        help_text="Ex : A1, B3, C12",
                        max_length=20,
                        verbose_name="Emplacement",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "fournisseur_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matieres_principales",
                        to="produits.fournisseur",
                        verbose_name="Fournisseur principal",
                    ),
                ),
                (
                    "unite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matieres",
                        to="produits.unitesmesure",
                        verbose_name="Unité de mesure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière première",
                "verbose_name_plural": "Matières premières",
                "ordering": ["reference"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="produits_ma_referen_89e966_idx"
                    ),
                    models.Index(
                        fields=["categorie"], name="produits_ma_categor_87cdd8_idx"
                    ),
                    models.Index(
                        fields=["methode_approvisionnement"],
                        name="produits_ma_methode_b5aeac_idx",
                    ),
                ],
            },
        ),
    ]
