# Generated by Django 4.2.21 on 2026-04-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matierepremiere",
            name="classe_abc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Classe A — Articles critiques (forte valeur)"),
                    ("B", "Classe B — Articles intermédiaires"),
                    ("C", "Classe C — Articles à faible valeur"),
                ],
                default="",
                help_text="Calculée automatiquement par la commande 'calculer_abc'. A = forte valeur (0–80 %), B = intermédiaire (80–95 %), C = faible valeur (95–100 %).",
                max_length=1,
                verbose_name="Classe ABC",
            ),
        ),
    ]
