# Generated by Django 4.2.21 on 2026-04-25 22:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0002_add_classe_abc"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitFini",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Ex : PF-001, MED-042",
                        max_length=30,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("MEDICAMENT", "Médicament"),
                            ("DISPOSITIF", "Dispositif médical"),
                            ("CONSOMMABLE", "Consommable"),
                            ("AUTRE", "Autre"),
                        ],
                        default="MEDICAMENT",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_PRODUCTION", "En production"),
                            ("DISPONIBLE", "Disponible"),
                            ("PERIME", "Périmé"),
                            ("RAPPEL", "Rappel produit"),
                            ("QUARANTAINE", "Quarantaine"),
                        ],
                        default="DISPONIBLE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "stock_actuel",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock actuel",
                    ),
                ),
                (
                    "stock_minimum",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock minimum",
                    ),
                ),
                (
                    "stock_maximum",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Stock maximum",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix unitaire (DH)",
                    ),
                ),
                (
                    "zone_stockage",
                    models.CharField(
                        choices=[
                            ("FROIDE", "Zone froide (2 – 8 °C)"),
                            ("TEMPEREE", "Température ambiante (15 – 25 °C)"),
                            ("SECHE", "Zone sèche"),
                        ],
                        default="TEMPEREE",
                        max_length=10,
                        verbose_name="Zone de stockage",
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True,
                        help_text="Ex : A1, PF-B3",
                        max_length=20,
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "numero_lot",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de lot"
                    ),
                ),
                (
                    "date_peremption",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de péremption"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "unite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produits_finis",
                        to="produits.unitesmesure",
                        verbose_name="Unité de mesure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit fini",
                "verbose_name_plural": "Produits finis",
                "ordering": ["reference"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="produits_pr_referen_e41923_idx"
                    ),
                    models.Index(
                        fields=["statut"], name="produits_pr_statut_a2dcc4_idx"
                    ),
                    models.Index(
                        fields=["categorie"], name="produits_pr_categor_c57523_idx"
                    ),
                ],
            },
        ),
    ]
