# Generated by Django 4.2.21 on 2026-04-25 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0003_add_produit_fini"),
    ]

    operations = [
        migrations.AddField(
            model_name="matierepremiere",
            name="lot_minimum",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Quantité minimale à commander si un besoin est détecté",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Lot minimum",
            ),
        ),
        migrations.AddField(
            model_name="matierepremiere",
            name="multiple_lot",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="La commande doit être un multiple de cette quantité",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Multiple de lot",
            ),
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_par_unite",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Quantité de matière nécessaire pour fabriquer 1 unité de produit fini",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(1e-06)],
                        verbose_name="Quantité par unité",
                    ),
                ),
                (
                    "taux_perte",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Perte additionnelle pour ce produit spécifique (ex: 0.05 pour 5%)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Taux de perte spécifique (%)",
                    ),
                ),
                (
                    "obligatoire",
                    models.BooleanField(default=True, verbose_name="Obligatoire"),
                ),
                (
                    "ordre_affichage",
                    models.PositiveSmallIntegerField(default=10, verbose_name="Ordre"),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilise_dans",
                        to="produits.matierepremiere",
                        verbose_name="Matière première / Composant",
                    ),
                ),
                (
                    "produit_fini",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composants",
                        to="produits.produitfini",
                        verbose_name="Produit fini",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de nomenclature",
                "verbose_name_plural": "Nomenclatures",
                "ordering": ["produit_fini", "ordre_affichage"],
                "unique_together": {("produit_fini", "matiere")},
            },
        ),
    ]
