# Generated by Django 4.2.21 on 2026-04-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0004_add_nomenclature_mrp"),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseur",
            name="statut",
            field=models.CharField(
                choices=[
                    ("ACTIF", "Actif"),
                    ("A_SURVEILLER", "À surveiller"),
                    ("INACTIF", "Inactif"),
                    ("BLOQUE", "Bloqué"),
                ],
                default="ACTIF",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
