# Generated by Django 4.2.21 on 2026-04-26 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0005_fournisseur_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitesmesure",
            name="autorise_decimales",
            field=models.BooleanField(
                default=True,
                help_text="Décocher pour les unités discrètes (Boîte, Pièce, etc.) qui ne gèrent que des entiers.",
                verbose_name="Autorise les décimales",
            ),
        ),
        migrations.AlterField(
            model_name="matierepremiere",
            name="lot_minimum",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Quantité minimale à commander si un besoin est détecté",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Lot minimum",
            ),
        ),
        migrations.AlterField(
            model_name="matierepremiere",
            name="multiple_lot",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="La commande doit être un multiple de cette quantité",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Multiple de lot",
            ),
        ),
    ]
