# Generated by Django 4.2.21 on 2026-04-26 17:18

from django.db import migrations, models
import django.db.models.deletion

def migrate_data(apps, schema_editor):
    LigneNomenclature = apps.get_model('produits', 'LigneNomenclature')
    Nomenclature = apps.get_model('produits', 'Nomenclature')
    
    # Group existing LigneNomenclature by produit_fini and create Nomenclature
    lignes = LigneNomenclature.objects.all()
    for ligne in lignes:
        nom, created = Nomenclature.objects.get_or_create(
            produit_fini=ligne.produit_fini,
            defaults={
                'nom': f"Nomenclature V1 - {ligne.produit_fini.reference}",
                'version': 'V1',
                'actif': True
            }
        )
        ligne.nomenclature = nom
        ligne.save()

class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0006_unitesmesure_autorise_decimales_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nomenclature',
            new_name='LigneNomenclature',
        ),
        migrations.AlterModelOptions(
            name='lignenomenclature',
            options={'ordering': ['produit_fini', 'ordre_affichage'], 'verbose_name': 'Ligne de nomenclature', 'verbose_name_plural': 'Lignes de nomenclature'},
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('version', models.CharField(default='V1', max_length=20, verbose_name='Version')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='produits.produitfini', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Nomenclature',
                'verbose_name_plural': 'Nomenclatures',
                'ordering': ['-actif', 'produit_fini', '-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='lignenomenclature',
            name='nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='produits.nomenclature', verbose_name='Nomenclature'),
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='lignenomenclature',
            unique_together={('nomenclature', 'matiere')},
        ),
        migrations.RemoveField(
            model_name='lignenomenclature',
            name='produit_fini',
        ),
        migrations.AlterField(
            model_name='lignenomenclature',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='produits.nomenclature', verbose_name='Nomenclature'),
        ),
        migrations.AlterModelOptions(
            name='lignenomenclature',
            options={'ordering': ['nomenclature', 'ordre_affichage'], 'verbose_name': 'Ligne de nomenclature', 'verbose_name_plural': 'Lignes de nomenclature'},
        ),
    ]
